version: '3.8'
services:
  sandwich_db:
    image: postgres:16-alpine3.18
    container_name: sandwich_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - sandwichbar

  sandwich_mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: sandwich_sql-server
    restart: always
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - '1433:1433'
    networks:
      - sandwichbar

  sandwich_backend:
    build: ./
    container_name: sandwich_backend
    ports:
      - 8080:8080
    networks:
      - sandwichbar
volumes:
  pg:
    driver: local
networks:
  sandwichbar:
    name: sandwichbar_network