version: '3.8'
services:
  sandwich_db:
    image: postgres:16-alpine3.18
    container_name: sandwich-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - sandwichbar

  sandwich_backend:
    build: ./
    container_name: sandwich-backend
    ports:
      - 8080:8080
    networks:
      - sandwichbar
volumes:
  pg:
    driver: local
networks:
  sandwichbar:
    name: sandwichbar_network