version: '3.8'
services:
  sandwich_db:
    image: postgres:16-alpine3.18
    container_name: sandwich_db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - sandwichbar

volumes:
  pg:
    driver: local
networks:
  sandwichbar:
    name: sandwichbar_network
